### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by leleliu008** [android-js/sample-app#13]
```
05-09 03:06:02.312  2818  2818 D WebViewUrlWatcher: watchUrlIfNeeded, url: file:///android_asset/myapp/views/index.html
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE: events.js:167
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:       throw er; // Unhandled 'error' event
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:       ^
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE: Error: listen EADDRINUSE :::3000
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:     at Server.setupListenHandle [as _listen2] (net.js:1286:14)
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:     at listenInCluster (net.js:1334:12)
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:     at Server.listen (net.js:1421:7)
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:     at Object.<anonymous> (/data/data/com.androidjs.mypkg/files/myapp/node_modules/androidjs/lib/back.js:7:6)
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:     at Module._compile (internal/modules/cjs/loader.js:688:30)
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:     at Module.load (internal/modules/cjs/loader.js:598:32)
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:     at Module.require (internal/modules/cjs/loader.js:636:17)
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE: Emitted 'error' event at:
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:     at emitErrorNT (net.js:1313:8)
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:     at process._tickCallback (internal/process/next_tick.js:63:19)
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:     at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:     at startup (internal/bootstrap/node.js:286:19)
05-09 03:06:02.697  2818  2850 E NODEJS-MOBILE:     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**Comment by Chhekur** [comment]
This error occurs when you are running 2 or more apps created by `Android JS` at the same time.

join [Slack Channel](https://join.slack.com/t/androidjs/shared_invite/zt-e0y0u6z6-hZdwdv1zN9AMbDKxhp7NcQ) for support and discussion

Feel free to ask in case of any problem ; )
