### ISSUE TITLE
Cannot build APK (tried on Sample-App)

### ISSUE THREAD

**Issue by posteal** [android-js/sample-app#16]
Hello, I tried to build an APK on the sms-app but it failed with this error:
I'm on UBUNTU 20.04 LTS
NodeJS Version: 10.19.9
ppm version: 6.14.8

```
Data: 53971 KB :██████████████████████████████████████████████████ √
copying assets ...
updating app name...
Setting app version ...
Version Code: 1
Version Name: 1.0
updating theme ...
theme attribute not found in package.json
Using SDK: 2.1.0
Building Apk ...
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Comment by DeveshPankaj** [comment]
make sure you have `JDK` installed in your system
 JDK > 1.8

**Comment by posteal** [comment]
Works now, thank you very much.
